version: '2'

services:
  gogs:
    image: gogs/gogs:0.11.43
    ports:
      - 23000:3000
      - 20022:22
    volumes:
      - gogs-data:/data
    environment:
      - GOGS_CUSTOM=/data/gogs
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 	

volumes:
  gogs-data:
